export const FETCH_QUALITIES = 'FETCH_QUALITIES';
export const SET_QUALITIES = 'SET_QUALITIES';
export const TOGGLE_SELECTED_QUALITY = 'TOGGLE_SELECTED_QUALITY';
export const EDIT_SELECTED_QUALITIES = 'EDIT_SELECTED_QUALITIES';
