export const FETCH_QUALITIES = 'FETCH_QUALITIES';
export const SET_QUALITIES = 'SET_QUALITIES';
export const TOGGLE_SELECTED_QUALITY_ON = 'TOGGLE_SELECTED_QUALITY_ON';
export const TOGGLE_SELECTED_QUALITY_OFF = 'TOGGLE_SELECTED_QUALITY_OFF';